### ISSUE TITLE
SpriteBatches seem to always draw in from of the 3d scene.

### ISSUE THREAD

**Issue by cdoty** [fredakilla/GPlayEngine#5]
If I create a full screen SpriteBatch, it obscures the 3D scene, even when rendered before calling Scene->visit. I can draw the SpriteBatch with 50% alpha, and the 3D scene is visible, indicating it's not a depth buffer issue.

**Comment by fredakilla** [comment]
Yes it's the default behavior for SpriteBatch because it use an internal default orthographic projection matrix.

You can override this by setting your own projection matrix or the current camera one for example in a 3d scene :

```
_spriteBatch->setProjectionMatrix(_scene->getActiveCamera()->getViewProjectionMatrix());
_spriteBatch->getMaterial()->getStateBlock()->setDepthTest(true);

_spriteBatch->start();
_spriteBatch->draw(Rectangle(0,0,1.0,1.0), Rectangle(0,0,256,256), Vector4::fromColor(0xaaaaaaaa));
// or
//_spriteBatch->draw(Vector3(0,0,0), Rectangle(0,0,256,256), Vector2(1,1), Vector4::fromColor(0xaaaaaaaa));
_spriteBatch->finish();
```
